export const Searchdata = [
  {
    id: 1,
    imageUrl:"https://media-cdn.tripadvisor.com/media/attractions-splice-spp-674x446/14/cb/3b/ca.jpg",
    location: "Mumbai",
    type: "4bhk",
    rent: "$1300 - $1600",
    sqfeet:"2096"
  },
  {
    id: 2,
    imageUrl:"https://media-cdn.tripadvisor.com/media/attractions-splice-spp-674x446/14/cb/3b/ca.jpg",
    location: "Pune",
    type: "House",
    rent: "$1900 - $2300",
  },
  {
    id: 3,
    imageUrl:"https://media-cdn.tripadvisor.com/media/attractions-splice-spp-674x446/14/cb/3b/ca.jpg",
    location: "Bangalore",
    type: "2bhk",
    rent: "$1700 - $2100",
  },
  {
    id: 4,
    imageUrl:"https://media-cdn.tripadvisor.com/media/attractions-splice-spp-674x446/14/cb/3b/ca.jpg",
    location: "Hyderabad",
    type: "2bhk",
    rent: "$1500 - $2000",
  },
  
  {
    id: 5,
    imageUrl:"https://media-cdn.tripadvisor.com/media/attractions-splice-spp-674x446/14/cb/3b/ca.jpg",
    location: "Ahmedabad",
    type: "2bhk",
    rent: "$1400 - $1700",
  },
  {
    id: 21,
    imageUrl:"https://media-cdn.tripadvisor.com/media/attractions-splice-spp-674x446/14/cb/3b/ca.jpg",
    location: "Hyderabad",
    type: "2bhk",
    rent: "$1500 - $2000",
  },
  {
    id: 6,
    imageUrl:"https://media-cdn.tripadvisor.com/media/attractions-splice-spp-674x446/14/cb/3b/ca.jpg",
    location: "Jaipur",
    type: "2bhk",
    rent: "$1800 - $2200",
  },
  {
    id: 7,
    imageUrl:"https://media-cdn.tripadvisor.com/media/attractions-splice-spp-674x446/14/cb/3b/ca.jpg",
    location: "Kolkata",
    type: "2bhk",
    rent: "$1600 - $2000",
  },
  {
    id: 8,
    imageUrl:"https://media-cdn.tripadvisor.com/media/attractions-splice-spp-674x446/14/cb/3b/ca.jpg",
    location: "Chennai",
    type: "2bhk",
    rent: "$1200 - $1500",
  },
  {
    id: 9,
    imageUrl:"https://media-cdn.tripadvisor.com/media/attractions-splice-spp-674x446/14/cb/3b/ca.jpg",
    location: "Lucknow",
    type: "2bhk",
    rent: "$1800 - $2200",
  },
  {
    id: 10,
    imageUrl:"https://media-cdn.tripadvisor.com/media/attractions-splice-spp-674x446/14/cb/3b/ca.jpg",
    location: "Indore",
    type: "2bhk",
    rent: "$1600 - $2000",
  },
  {
    id: 11,
    imageUrl:"https://media-cdn.tripadvisor.com/media/attractions-splice-spp-674x446/14/cb/3b/ca.jpg",
    location: "Bhopal",
    type: "2bhk",
    rent: "$1300 - $1600",
  },
  {
    id: 12,
    imageUrl:"https://media-cdn.tripadvisor.com/media/attractions-splice-spp-674x446/14/cb/3b/ca.jpg",
    location: "Surat",
    type: "2bhk",
    rent: "$1200 - $1500",
  },
  {
    id: 13,
    imageUrl:"https://media-cdn.tripadvisor.com/media/attractions-splice-spp-674x446/14/cb/3b/ca.jpg",
    location: "Nagpur",
    type: "2bhk",
    rent: "$1500 - $1900",
  },
  {
    id: 14,
    imageUrl:"https://media-cdn.tripadvisor.com/media/attractions-splice-spp-674x446/14/cb/3b/ca.jpg",
    location: "Visakhapatnam",
    type: "2bhk",
    rent: "$1600 - $2100",
  },
  {
    id: 15,
    imageUrl:"https://media-cdn.tripadvisor.com/media/attractions-splice-spp-674x446/14/cb/3b/ca.jpg",
    location: "Vadodara",
    type: "2bhk",
    rent: "$1400 - $1800",
  },
  {
    id: 16,
    imageUrl:"https://media-cdn.tripadvisor.com/media/attractions-splice-spp-674x446/14/cb/3b/ca.jpg",
    location: "Ludhiana",
    type: "2bhk",
    rent: "$1600 - $2100",
  },
  {
    id: 17,
    imageUrl:"https://media-cdn.tripadvisor.com/media/attractions-splice-spp-674x446/14/cb/3b/ca.jpg",
    location: "Agra",
    type: "2bhk",
    rent: "$1300 - $1700",
  },
  {
    id: 18,
    imageUrl:"https://media-cdn.tripadvisor.com/media/attractions-splice-spp-674x446/14/cb/3b/ca.jpg",
    location: "Coimbatore",
    type: "2bhk",
    rent: "$1400 - $1750",
  },
  {
    id: 19,
    imageUrl:"https://media-cdn.tripadvisor.com/media/attractions-splice-spp-674x446/14/cb/3b/ca.jpg",
    location: "Thane",
    type: "2bhk",
    rent: "$1600 - $2100",
  },
  {
    id: 20,
    imageUrl:"https://media-cdn.tripadvisor.com/media/attractions-splice-spp-674x446/14/cb/3b/ca.jpg",
    location: "Patna",
    type: "2bhk",
    rent: "$1200 - $1500",
  }
];

export default Searchdata;